#define ERROR_LOCATION __FILE__, __LINE__

#ifdef __GFORTRAN__
#define CHECK_TRUE(EXPR, FORMAT) call ASSERT_TRUE(EXPR, FORMAT, ERROR_LOCATION)
#define CHECK_EQUAL(VALUE, EXPECTED, FORMAT) call ASSERT_EQUAL(VALUE, EXPECTED, FORMAT, ERROR_LOCATION)
#define CHECK_FLOAT_EQUAL(VALUE, EXPECTED, FORMAT) call ASSERT_FLOAT_EQUAL(VALUE, EXPECTED, FORMAT, ERROR_LOCATION)
#else
#define CHECK_TRUE(EXPR, MSG) call ASSERT_TRUE(EXPR, MSG, ERROR_LOCATION)
#define CHECK_EQUAL(VALUE, EXPECTED, FORMAT) call ASSERT_EQUAL(VALUE, EXPECTED, FORMAT, ERROR_LOCATION)
#define CHECK_FLOAT_EQUAL(VALUE, EXPECTED, FORMAT) call ASSERT_FLOAT_EQUAL(VALUE, EXPECTED, FORMAT, ERROR_LOCATION)
#endif
